# Generated by Django 4.2.30 on 2026-06-08 19:17

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('papel', models.CharField(choices=[('GESTOR_PROJETO', 'Gestor de Projeto'), ('COLABORADOR', 'Colaborador')], default='COLABORADOR', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído'), ('ARQUIVADO', 'Arquivado')], default='ATIVO', max_length=20)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_criados', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('POR_INICIAR', 'Por iniciar'), ('EM_EXECUCAO', 'Em execução'), ('CONCLUIDA', 'Concluída')], default='POR_INICIAR', max_length=20)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('esforco_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Esforço estimado (h)')),
                ('esforco_real', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Esforço real (h)')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_atribuidas', to=settings.AUTH_USER_MODEL)),
                ('tarefa_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='core.tarefa')),
            ],
            options={
                'ordering': ['tarefa_pai__id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DependenciaTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predecessora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_como_predecessora', to='core.tarefa')),
                ('sucessora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_como_sucessora', to='core.tarefa')),
            ],
            options={
                'unique_together': {('predecessora', 'sucessora')},
            },
        ),
    ]
