# Generated by Django 4.2.30 on 2026-06-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
    ]
